### PR TITLE
[`stubtest`] don't call the `__bool__` of default function params

### PR DESCRIPTION
**Pull request by jorenham**
image
... not sure what happened here, but this baby platypus wanted to be in this PR for some reason 🤷🏻 

---

This is currently causing `stubtest` to crash when running it on `scipy-stubs` with the latest [`numpy==2.2.0`](https://github.com/numpy/numpy/releases/tag/v2.2.0) release:

```shell
$ stubtest --mypy-config-file=pyproject.toml --allowlist=.mypyignore --ignore-unused-allowlist scipy
Traceback (most recent call last):
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/bin/stubtest", line [8](https://github.com/jorenham/scipy-stubs/actions/runs/12246812991/job/34163454128?pr=288#step:7:9), in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mypy/stubtest.py", line 20[9](https://github.com/jorenham/scipy-stubs/actions/runs/12246812991/job/34163454128?pr=288#step:7:10)8, in main
    return test_stubs(parse_options(sys.argv[1:]))
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mypy/stubtest.py", line 1971, in test_stubs
    for error in test_module(module):
                 ~~~~~~~~~~~^^^^^^^^
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mypy/stubtest.py", line 247, in test_module
    yield from verify(stub, runtime, [module_name])
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mypy/stubtest.py", line 423, in verify_mypyfile
    yield from verify(stub_entry, runtime_entry, object_path + [entry])
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mypy/stubtest.py", line 578, in verify_typeinfo
    yield from verify(stub_to_verify, runtime_attr, object_path + [entry])
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mypy/stubtest.py", line [10](https://github.com/jorenham/scipy-stubs/actions/runs/12246812991/job/34163454128?pr=288#step:7:11)64, in verify_funcitem
    for message in _verify_signature(stub_sig, runtime_sig, function_name=stub.name):
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.[13](https://github.com/jorenham/scipy-stubs/actions/runs/12246812991/job/34163454128?pr=288#step:7:14)/site-packages/mypy/stubtest.py", line 902, in _verify_signature
    yield from _verify_arg_default_value(stub_arg, runtime_arg)
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mypy/stubtest.py", line 664, in _verify_arg_default_value
    if runtime_arg.default != inspect.Parameter.empty:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The truth value of an empty array is ambiguous. Use `array.size > 0` to check that an array is not empty.
Error: Process completed with exit code 1.
```

relevant [`scipy-stubs`](https://github.com/jorenham/scipy-stubs) PR: https://github.com/jorenham/scipy-stubs/pull/288

### CODE REVIEW

**Comment by KotlinIsland** [comment]
not trying to be a pedant, but could you remove the emoji from the commit message?

**Comment by KotlinIsland** [comment]
and add a changelog entry :)

**Review by KotlinIsland — APPROVED** [review]

**Comment by KotlinIsland** [comment]
if you can think of how to test this go for it, otherwise i don't think it's needed

**Comment by jorenham** [comment]
> not trying to be a pedant, but could you remove the emoji from the commit message?

Not a [gitmoji](https://gitmoji.dev/) fan eh?

**Comment by KotlinIsland** [comment]
i can release this asap once it's merged

**Comment by jorenham** [comment]
> and add a changelog entry :)

✅

**Comment by jorenham** [comment]
I'll add a test as well

**Comment by jorenham** [comment]
> I'll add a test as well

✅

**Comment by jorenham** [comment]
> Ehh I don't really understand what's causing the CI to act up 🤔

is it type-checking the evaluated `runtime` source string or something?

**Comment by KotlinIsland** [comment]
you might need to run `./pw write-baseline`

**Comment by jorenham** [comment]
> you might need to run `./pw write-baseline`

after `python pw install` successfully ran, I got

```
python pw write-baseline
/bin/sh: 1: mypy: not found
```

**Comment by KotlinIsland** [comment]
> still the same initial issue btw
> 
> ```shell
> $ ./pw write-baseline
> /bin/sh: 1: mypy: not found
> ```

- #844

**Comment by jorenham** [comment]
> > still the same initial issue btw
> > ```shell
> > $ ./pw write-baseline
> > /bin/sh: 1: mypy: not found
> > ```
> 
> * [add pyprojectx venv config #844](https://github.com/KotlinIsland/basedmypy/pull/844)

This didn't solve it "en sich*, but by additionally setting

```
_typecheck = "uv run --no-project mypy --config-file mypy_self_check.ini -p mypy -p mypyc"
```

I managed to get this working

**Pull request merged**
